# Build Definition
# Build the complete solution and get ready for deployment

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.3.1'
  displayName: 'Use v5.3.1 of NuGet'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
  displayName: 'Restore Nuget Packages'
- task: MSBuild@1
  inputs:
    solution: 'JMovies.sln'
    configuration: 'Release' 
    msbuildArguments: /p:DeployOnBuild=true /p:PublishProfile="JMovies.App.Local.pubxml"
  displayName: 'Build and Deploy Locally App Layer'
- task: MSBuild@1
  inputs:
    solution: 'JMovies.Web.UI/JMovies.Web.UI.csproj'
    configuration: 'Release' 
    msbuildArguments: '/p:Configuration=Release /t:publish /p:PublishDir="Release" /p:PublishProfile="JMovies.Web.UI.Local.pubxml"'
  displayName: 'Deploy Locally Web Layer'
- task: MSBuild@1
  inputs:
    solution: 'Jobs/JMovies.Jobs.IMDB.ProductionPersister/JMovies.Jobs.IMDB.ProductionPersister.csproj'
    configuration: 'Release' 
    msbuildArguments: '/p:PublishDir="Release" /t:publish /p:Configuration=Release /p:PublishProfile="JMovies.Jobs.IMDB.ProductionPersister.Local.pubxml"'
  displayName: 'Deploy Locally IMDB Production Persister'
- task: MSBuild@1
  inputs:
    solution: 'Jobs/JMovies.Jobs.IMDB.PersonPersister/JMovies.Jobs.IMDB.PersonPersister.csproj'
    configuration: 'Release' 
    msbuildArguments: '/p:PublishDir="Release" /t:publish /p:Configuration=Release /p:PublishProfile="JMovies.Jobs.IMDB.PersonPersister.Local.pubxml"'
  displayName: 'Deploy Locally IMDB Person Persister'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'JMovies.App/Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app'
  displayName: 'Add App Release Files to Artifacts'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'JMovies.Web.UI/Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/web'
  displayName: 'Add Web Release Files to Artifacts'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'Jobs/JMovies.Jobs.IMDB.ProductionPersister/Release/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Jobs/imdbProductionPersister'
  displayName: 'Add IMDB Production Persister Release Files to Artifacts'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'Jobs/JMovies.Jobs.IMDB.PersonPersister/Release/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Jobs/imdbPersonPersister'
  displayName: 'Add IMDB Person Persister Release Files to Artifacts'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'