//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMovies.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JMMovie
    {
        public string ID { get; set; }
        public Nullable<long> IMDBID { get; set; }
        public int ProductionType { get; set; }
        public string Title { get; set; }
        public string OriginalTitle { get; set; }
        public int Year { get; set; }
        public Nullable<int> EndYear { get; set; }
        public string PlotSummary { get; set; }
        public string StoryLine { get; set; }
        public Nullable<System.TimeSpan> Runtime { get; set; }
    }
}
